type = "publication"
title = "Publications"
description = "A collection of my research work. [Google Scholar](https://scholar.google.com/citations?user=n4hAXN8AAAAJ&hl=en). * denotes corresponding author, † denotes equal contribution."
source = "publications.bib"
